builds:
  - main: main.go
    binary: gct
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^tweak'
      - '^test'
brews:
  - tap:
      owner: zcong1993
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/zcong1993/gcommitter
    description: Easy way of git commit and push
    test: |
      system "#{bin}/gct -v"
